name: smart_akshaya
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  excel: ^4.0.6
  flutter_dotenv: ^5.1.0
  file_picker: ^11.0.2
  crypto: ^3.0.7
  http: ^1.6.0
  url_launcher: ^6.3.2
  html: ^0.15.6
  syncfusion_flutter_pdfviewer: ^33.2.10
  image: ^4.3.0
  crop_image: ^1.0.17
  pdf: ^3.12.0
  printing: ^5.14.3
  file_selector: ^1.1.0
  file_selector_windows: ^0.9.3+5
  uuid: ^4.2.1
  window_manager: ^0.3.9
  provider: ^6.1.1

dependency_overrides:
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/credentials/
    - .env
    - assets/forms/
    - assets/forms_data.json
    - assets/templates/
